version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: python3 manage.py runserver 0.0.0.0:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres
    env_file:
      - ./.env.dev
    volumes: 
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis

  celery:
    restart: always
    build:
      context: .
    command: celery -A app worker -l info
    volumes:
      - ./app:/app
    env_file:
      - ./.env.dev
    depends_on:
      - redis
      - app

  celery-beat:
    restart: always
    build:
      context: .
    command: celery -A app beat -l info
    volumes:
      - ./app:/app
    env_file:
      - ./.env.dev
    depends_on:
      - redis
      - app

  flower:
    image: mher/flower:0.9.5
    command: [ 'flower', '--broker=redis://redis:6379', '--port=5555' ]
    ports:
      - 5555:5555
    expose:
      - 5555
    depends_on:
      - celery

volumes:
  pgdata: